name: icl
channels:
  - defaults
dependencies:
  - pip
  - python=3.8.12
  - pip:
    - ipykernel
    - ipywidgets
    - matplotlib
    - pandas
    - quinine
    - scikit-learn
    - seaborn
    - torch
    - transformers
    - wandb
    - xgboost
    - protobuf
    - einops
    - munch
